"""V3.5 method inventory.

non-runtime contract metadata only; no handler registration; no behavior change
"""

from __future__ import annotations

from typing import Any, Dict, List

MethodEntry = Dict[str, Any]


METHOD_INVENTORY: List[MethodEntry] = [
    {
        "method": "session.start",
        "surface": "default",
        "status": "implemented",
        "capability": "sessions",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.session_start",
        "forbidden_reason": None,
    },
    {
        "method": "turn.start",
        "surface": "default",
        "status": "implemented",
        "capability": "turns",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.turn_start",
        "forbidden_reason": None,
    },
    {
        "method": "events.subscribe",
        "surface": "default",
        "status": "implemented",
        "capability": "events",
        "stability": "beta",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.events_subscribe",
        "forbidden_reason": None,
    },
    {
        "method": "artifact.list",
        "surface": "default",
        "status": "implemented",
        "capability": "artifacts",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.artifact_list",
        "forbidden_reason": None,
    },
    {
        "method": "artifact.read_metadata",
        "surface": "default",
        "status": "implemented",
        "capability": "artifacts",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.artifact_read_metadata",
        "forbidden_reason": None,
    },
    {
        "method": "artifact.register_external",
        "surface": "default",
        "status": "implemented",
        "capability": "artifacts",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.artifact_register_external",
        "forbidden_reason": None,
    },
    {
        "method": "artifact.lineage",
        "surface": "default",
        "status": "implemented",
        "capability": "artifact_lineage",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.artifact_lineage",
        "forbidden_reason": None,
    },
    {
        "method": "job.get",
        "surface": "default",
        "status": "implemented",
        "capability": "jobs",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.job_get",
        "forbidden_reason": None,
    },
    {
        "method": "job.list",
        "surface": "default",
        "status": "implemented",
        "capability": "jobs",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.job_list",
        "forbidden_reason": None,
    },
    {
        "method": "approval.respond",
        "surface": "default",
        "status": "implemented",
        "capability": "approvals",
        "stability": "beta",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.approval_respond",
        "forbidden_reason": None,
    },
    {
        "method": "connector.health",
        "surface": "default",
        "status": "implemented",
        "capability": "connectors.read",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.connector_health",
        "forbidden_reason": None,
    },
    {
        "method": "pack.list",
        "surface": "default",
        "status": "implemented",
        "capability": "packs.read",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.pack_list",
        "forbidden_reason": None,
    },
    {
        "method": "pack.get",
        "surface": "default",
        "status": "implemented",
        "capability": "packs.read",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.pack_get",
        "forbidden_reason": None,
    },
    {
        "method": "method.list",
        "surface": "optional",
        "status": "implemented",
        "capability": "rpc",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.method_list",
        "forbidden_reason": None,
    },
    {
        "method": "initialize",
        "surface": "optional",
        "status": "implemented",
        "capability": "rpc",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.initialize",
        "forbidden_reason": None,
    },
    {
        "method": "health.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "health",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.health_*",
        "forbidden_reason": None,
    },
    {
        "method": "app.list",
        "surface": "optional",
        "status": "implemented",
        "capability": "apps",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.app_list",
        "forbidden_reason": None,
    },
    {
        "method": "app.get",
        "surface": "optional",
        "status": "implemented",
        "capability": "apps",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.app_get",
        "forbidden_reason": None,
    },
    {
        "method": "connector.list",
        "surface": "optional",
        "status": "implemented",
        "capability": "connectors",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.connector_list",
        "forbidden_reason": None,
    },
    {
        "method": "connector.get",
        "surface": "optional",
        "status": "implemented",
        "capability": "connectors",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.connector_get",
        "forbidden_reason": None,
    },
    {
        "method": "connector.submit",
        "surface": "optional",
        "status": "implemented",
        "capability": "connector_execution",
        "stability": "beta",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.connector_submit",
        "forbidden_reason": None,
    },
    {
        "method": "connector.poll",
        "surface": "optional",
        "status": "implemented",
        "capability": "connector_execution",
        "stability": "beta",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.connector_poll",
        "forbidden_reason": None,
    },
    {
        "method": "connector.collect",
        "surface": "optional",
        "status": "implemented",
        "capability": "connector_execution",
        "stability": "beta",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.connector_collect",
        "forbidden_reason": None,
    },
    {
        "method": "job.events",
        "surface": "optional",
        "status": "implemented",
        "capability": "job_events",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.job_events",
        "forbidden_reason": None,
    },
    {
        "method": "session.events",
        "surface": "optional",
        "status": "implemented",
        "capability": "stream_events",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.session_events",
        "forbidden_reason": None,
    },
    {
        "method": "workflow.list",
        "surface": "optional",
        "status": "implemented",
        "capability": "workflows",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.workflow_list",
        "forbidden_reason": None,
    },
    {
        "method": "policy.evaluate",
        "surface": "optional",
        "status": "implemented",
        "capability": "policies",
        "stability": "beta",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.policy_evaluate",
        "forbidden_reason": None,
    },
    {
        "method": "trace.list",
        "surface": "optional",
        "status": "implemented",
        "capability": "traces",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.trace_list",
        "forbidden_reason": None,
    },
    {
        "method": "trace.get",
        "surface": "optional",
        "status": "implemented",
        "capability": "traces",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.trace_get",
        "forbidden_reason": None,
    },
    {
        "method": "session.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "sessions",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.session_*",
        "forbidden_reason": None,
    },
    {
        "method": "thread.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "sessions",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.core_thread_*",
        "forbidden_reason": None,
    },
    {
        "method": "turn.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "turns",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.turn_*",
        "forbidden_reason": None,
    },
    {
        "method": "core.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "core",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.core_*",
        "forbidden_reason": None,
    },
    {
        "method": "artifact.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "artifacts",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.artifact_*",
        "forbidden_reason": None,
    },
    {
        "method": "approval.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "approvals",
        "stability": "beta",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.approval_*",
        "forbidden_reason": None,
    },
    {
        "method": "connector.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "connectors",
        "stability": "beta",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.connector_*",
        "forbidden_reason": None,
    },
    {
        "method": "job.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "jobs",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.job_*",
        "forbidden_reason": None,
    },
    {
        "method": "memory.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "memory",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.memory_*",
        "forbidden_reason": None,
    },
    {
        "method": "workflow.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "workflows",
        "stability": "beta",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.workflow_*",
        "forbidden_reason": None,
    },
    {
        "method": "pack.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "packs",
        "stability": "beta",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.pack_*",
        "forbidden_reason": None,
    },
    {
        "method": "agent.*",
        "surface": "optional",
        "status": "implemented",
        "capability": "agents",
        "stability": "stable",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.agent_*",
        "forbidden_reason": None,
    },
    {
        "method": "meeting.*",
        "surface": "forbidden_by_default",
        "status": "legacy",
        "capability": "meeting",
        "stability": "legacy",
        "planned_phase": None,
        "handler_ref": None,
        "forbidden_reason": "business-specific legacy facade; use pack workflow or BFF composition",
    },
    {
        "method": "knowledge.*",
        "surface": "forbidden_by_default",
        "status": "legacy",
        "capability": "knowledge",
        "stability": "legacy",
        "planned_phase": None,
        "handler_ref": None,
        "forbidden_reason": "business-specific facade; use data_service connector through pack/BFF",
    },
    {
        "method": "pack.execute_stub",
        "surface": "forbidden_by_default",
        "status": "debug",
        "capability": "pack_execution",
        "stability": "debug",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.pack_execute_stub",
        "forbidden_reason": "stub/debug execution path is not SDK default surface",
    },
    {
        "method": "workflow.execute_stub",
        "surface": "forbidden_by_default",
        "status": "debug",
        "capability": "pack_execution",
        "stability": "debug",
        "planned_phase": None,
        "handler_ref": "apps.gateway.service.GatewayService.workflow_execute_stub",
        "forbidden_reason": "stub/debug execution path is not SDK default surface",
    },
    {
        "method": "debug.*",
        "surface": "forbidden_by_default",
        "status": "debug",
        "capability": "debug",
        "stability": "debug",
        "planned_phase": None,
        "handler_ref": None,
        "forbidden_reason": "debug-only methods cannot be SDK default surface",
    },
    {
        "method": "admin.*",
        "surface": "forbidden_by_default",
        "status": "debug",
        "capability": "admin",
        "stability": "debug",
        "planned_phase": None,
        "handler_ref": None,
        "forbidden_reason": "admin bypass methods cannot be SDK default surface",
    },
    {
        "method": "test.*",
        "surface": "forbidden_by_default",
        "status": "debug",
        "capability": "tests",
        "stability": "debug",
        "planned_phase": None,
        "handler_ref": None,
        "forbidden_reason": "test-only methods cannot be SDK default surface",
    },
]


FORBIDDEN_BUSINESS_WRAPPERS = (
    "generateMinutes",
    "ingestDocument",
    "runMeetingWorkflow",
    "generateVideo",
    "analyzePortfolio",
    "processRecording",
    "searchKnowledgeBase",
)
